import { useState, type ChangeEvent, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { analyzeTrendCsv } from '../lib/api';
import type { SiteLang, TrendCandle, TrendPayload } from '../types';

const TREND_TOOL_SLUG = 'trend-analyzer';
const TREND_FETCHER_REPO_URL = 'https://github.com/garmlegarmle/ga-ml-trend-fetcher';
const TREND_FETCHER_LOCAL_RUN_URL = `${TREND_FETCHER_REPO_URL}#local-run`;
const TREND_FETCHER_MAC_URL = `${TREND_FETCHER_REPO_URL}/releases/latest/download/GA-ML-TrendFetcher-macos.zip`;
const TREND_FETCHER_WINDOWS_URL = `${TREND_FETCHER_REPO_URL}/releases/latest/download/GA-ML-TrendFetcher-windows.zip`;

const TOOL_COPY = {
  en: {
    featureEyebrow: 'Built-in Tool',
    featureTitle: 'Trend Analyzer',
    featureDescription:
      'Upload the downloader-generated OHLCV CSV to inspect the last 200 daily candles, moving averages, Ichimoku, MACD, RSI, and the current regime readout.',
    featureCta: 'Open tool',
    eyebrow: 'Tool / Market Trend',
    title: 'Trend Analyzer',
    description:
      'Upload the CSV generated by the desktop downloader. The server analyzes it once, returns a chart-ready payload, and discards the uploaded file immediately.',
    fileLabel: 'Downloader CSV file',
    fileHint: 'Upload the CSV generated by the GA-ML Trend Fetcher downloader.',
    fileButton: 'Choose CSV',
    fileEmpty: 'No file selected',
    submit: 'Analyze CSV',
    processing: 'Analyzing...',
    privacyNotice: 'Uploaded CSV files are processed once and removed immediately. We do not store them in the database.',
    downloadTitle: 'Desktop downloader',
    downloadBody: 'Use the standalone app to generate the CSV locally, then upload that file here.',
    downloadNote:
      'macOS may block the first launch because the current build is unsigned. Use Control-click > Open, or allow it once from Privacy & Security.',
    pythonGuide: 'Python setup guide',
    pythonIntro: 'If the unsigned app is blocked, you can run the downloader directly with Python:',
    pythonCommands: [
      'git clone https://github.com/garmlegarmle/ga-ml-trend-fetcher.git',
      'cd ga-ml-trend-fetcher',
      'python3 -m venv .venv',
      'source .venv/bin/activate',
      'pip install -r requirements.txt',
      'python main.py'
    ],
    macDownload: 'macOS app',
    windowsDownload: 'Windows app',
    repoLink: 'Source repo',
    activeTicker: 'Ticker',
    fileStatus: 'Current file',
    asOf: 'As of',
    window: 'Window',
    chartTitle: 'Candles + Indicator Stack',
    chartSubtitle: 'Last 200 daily sessions with moving averages, Ichimoku, MACD, and RSI',
    keySummaryTitle: 'Key Summary',
    resultTitle: 'Analysis Result',
    summaryTitle: 'Interpretation',
    snapshotTitle: 'Latest Snapshot',
    trend: 'Trend',
    strength: 'Trend strength',
    conviction: 'Trend conviction',
    risk: 'Transition risk',
    confidence: 'Confidence',
    direction: 'Direction score',
    momentum: 'Momentum score',
    volatility: 'Volatility regime',
    volume: 'Volume confirmation',
    noDataTitle: 'Upload the downloader CSV to start',
    noDataBody: 'Generate a CSV with the desktop downloader, then upload that file here.',
    lastClose: 'Last close',
    lowLabel: 'Low',
    midLabel: 'Mid',
    highLabel: 'High',
    bearishLabel: 'Bearish',
    neutralLabel: 'Neutral',
    bullishLabel: 'Bullish',
    stableLabel: 'Stable',
    elevatedLabel: 'Elevated',
    riskHighLabel: 'High risk',
    rangeLabel: 'Range',
    zoneLabel: 'Current zone',
    ema20Legend: 'EMA 20',
    ema50Legend: 'EMA 50',
    sma200Legend: 'SMA 200',
    tenkanLegend: 'Tenkan',
    kijunLegend: 'Kijun',
    cloudLegend: 'Cloud',
    macdLegend: 'MACD',
    signalLegend: 'Signal',
    rsiLegend: 'RSI'
  },
  ko: {
    featureEyebrow: '내장 도구',
    featureTitle: '추세 분석기',
    featureDescription:
      '다운로더가 만든 OHLCV CSV를 업로드하면 최근 200일 일봉, 이동평균선, 일목균형표, MACD, RSI와 현재 추세 판독 결과를 확인할 수 있습니다.',
    featureCta: '도구 열기',
    eyebrow: '도구 / 주식 추세',
    title: '추세 분석기',
    description:
      '데스크톱 다운로더가 만든 CSV 파일을 업로드하면 서버에서 한 번만 분석하고, 차트용 payload만 돌려준 뒤 업로드 파일은 즉시 폐기합니다.',
    fileLabel: '다운로더 CSV 파일',
    fileHint: 'GA-ML Trend Fetcher 다운로더가 만든 CSV 파일을 업로드해 주세요.',
    fileButton: 'CSV 선택',
    fileEmpty: '선택한 파일 없음',
    submit: 'CSV 분석하기',
    processing: '분석 중...',
    privacyNotice: '업로드한 CSV는 한 번만 분석하고 즉시 삭제합니다. 데이터베이스에 계속 저장하지 않습니다.',
    downloadTitle: '데스크톱 다운로더',
    downloadBody: '독립 실행 앱으로 로컬 CSV를 만든 뒤, 그 파일을 이 화면에 업로드해서 분석하세요.',
    downloadNote:
      '현재 macOS 빌드는 서명되지 않아 첫 실행 시 차단될 수 있습니다. Control-클릭 후 열기 또는 개인 정보 보호 및 보안에서 한 번 허용해 주세요.',
    pythonGuide: 'Python 실행 안내',
    pythonIntro: 'unsigned 앱이 막히면 아래처럼 Python으로 직접 실행할 수 있습니다:',
    pythonCommands: [
      'git clone https://github.com/garmlegarmle/ga-ml-trend-fetcher.git',
      'cd ga-ml-trend-fetcher',
      'python3 -m venv .venv',
      'source .venv/bin/activate',
      'pip install -r requirements.txt',
      'python main.py'
    ],
    macDownload: 'macOS 앱',
    windowsDownload: 'Windows 앱',
    repoLink: '소스 레포',
    activeTicker: '티커',
    fileStatus: '현재 파일',
    asOf: '기준일',
    window: '구간',
    chartTitle: '일봉 캔들 + 지표 차트',
    chartSubtitle: '최근 200개 일봉 세션에 이동평균선, 일목균형표, MACD, RSI를 함께 표시합니다.',
    keySummaryTitle: '핵심 요약',
    resultTitle: '분석 결과',
    summaryTitle: '해석',
    snapshotTitle: '최신 스냅샷',
    trend: '현재 추세',
    strength: '추세 강도',
    conviction: '추세 확신도',
    risk: '전환 위험',
    confidence: '신뢰도',
    direction: '방향 점수',
    momentum: '모멘텀 점수',
    volatility: '변동성 환경',
    volume: '거래량 확인도',
    noDataTitle: '다운로더 CSV를 업로드하면 결과가 나옵니다',
    noDataBody: '데스크톱 다운로더로 CSV를 만든 뒤 그 파일을 이 화면에 업로드해 주세요.',
    lastClose: '최근 종가',
    lowLabel: '낮음',
    midLabel: '중간',
    highLabel: '높음',
    bearishLabel: '하락',
    neutralLabel: '중립',
    bullishLabel: '상승',
    stableLabel: '안정',
    elevatedLabel: '주의',
    riskHighLabel: '고위험',
    rangeLabel: '범위',
    zoneLabel: '현재 구간',
    ema20Legend: 'EMA 20',
    ema50Legend: 'EMA 50',
    sma200Legend: 'SMA 200',
    tenkanLegend: '전환선',
    kijunLegend: '기준선',
    cloudLegend: '구름대',
    macdLegend: 'MACD',
    signalLegend: '시그널',
    rsiLegend: 'RSI'
  }
} as const;

type RangeMetric = {
  label: string;
  value: number;
  min: number;
  max: number;
  lowLabel: string;
  midLabel: string;
  highLabel: string;
  digits?: number;
  signed?: boolean;
};

type NumericSeries = Array<number | null | undefined>;

function isFiniteNumber(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value);
}

function formatDate(value: string | null | undefined, lang: SiteLang): string {
  if (!value) return '-';
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) return value;
  return new Date(parsed).toLocaleDateString(lang === 'ko' ? 'ko-KR' : 'en-US');
}

function formatNumber(value: number | null | undefined, lang: SiteLang, digits = 2): string {
  if (!isFiniteNumber(value)) return '-';
  return new Intl.NumberFormat(lang === 'ko' ? 'ko-KR' : 'en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: digits
  }).format(value);
}

function formatMetricValue(value: number, lang: SiteLang, digits = 1, signed = false): string {
  if (!isFiniteNumber(value)) return '-';
  const prefix = signed && value > 0 ? '+' : '';
  return `${prefix}${formatNumber(value, lang, digits)}`;
}

function titleCase(value: string): string {
  return String(value || '')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((chunk) => chunk.charAt(0).toUpperCase() + chunk.slice(1))
    .join(' ');
}

function clampPercent(value: number): number {
  return Math.max(0, Math.min(100, value));
}

function rangePosition(value: number, min: number, max: number): number {
  if (!isFiniteNumber(value) || max <= min) return 0;
  return clampPercent(((value - min) / (max - min)) * 100);
}

function buildSeriesPath(values: NumericSeries, xAt: (index: number) => number, scaleY: (value: number) => number): string {
  let path = '';
  let active = false;

  values.forEach((value, index) => {
    if (!isFiniteNumber(value)) {
      active = false;
      return;
    }
    const command = active ? 'L' : 'M';
    path += `${command} ${xAt(index).toFixed(2)} ${scaleY(value).toFixed(2)} `;
    active = true;
  });

  return path.trim();
}

function buildAreaPath(
  upperValues: NumericSeries,
  lowerValues: NumericSeries,
  xAt: (index: number) => number,
  scaleY: (value: number) => number
): string {
  const upperPoints: string[] = [];
  const lowerPoints: string[] = [];

  upperValues.forEach((upperValue, index) => {
    const lowerValue = lowerValues[index];
    if (!isFiniteNumber(upperValue) || !isFiniteNumber(lowerValue)) return;
    upperPoints.push(`${xAt(index).toFixed(2)} ${scaleY(upperValue).toFixed(2)}`);
    lowerPoints.push(`${xAt(index).toFixed(2)} ${scaleY(lowerValue).toFixed(2)}`);
  });

  if (upperPoints.length < 2 || lowerPoints.length < 2) return '';
  return `M ${upperPoints.join(' L ')} L ${lowerPoints.reverse().join(' L ')} Z`;
}

function buildChartTicks(candles: TrendCandle[]) {
  const midpoint = Math.floor(candles.length / 2);
  return [candles[0]?.date || '', candles[midpoint]?.date || '', candles[candles.length - 1]?.date || ''];
}

function fileNameOrFallback(file: File | null, fallback: string) {
  return file?.name || fallback;
}

function formatWindowLabel(bars: number, lang: SiteLang): string {
  return lang === 'ko' ? `${bars}개 세션` : `${bars} sessions`;
}

function buildRangeMeta(metric: RangeMetric, copy: (typeof TOOL_COPY)[SiteLang], lang: SiteLang): string {
  const position = rangePosition(metric.value, metric.min, metric.max);
  const zone = position < 33 ? metric.lowLabel : position < 66 ? metric.midLabel : metric.highLabel;
  return `${copy.rangeLabel}: ${formatMetricValue(metric.min, lang, 0, metric.signed)} to ${formatMetricValue(
    metric.max,
    lang,
    0,
    metric.signed
  )} | ${copy.zoneLabel}: ${zone}`;
}

function CombinedTrendChart({ candles, lang }: { candles: TrendCandle[]; lang: SiteLang }) {
  if (candles.length === 0) return null;

  const width = 1120;
  const left = 64;
  const right = 24;
  const top = 24;
  const priceHeight = 360;
  const macdHeight = 140;
  const rsiHeight = 118;
  const panelGap = 18;
  const bottom = 36;
  const plotWidth = width - left - right;
  const stepX = plotWidth / Math.max(candles.length, 1);
  const priceTop = top;
  const priceBottom = priceTop + priceHeight;
  const macdTop = priceBottom + panelGap;
  const macdBottom = macdTop + macdHeight;
  const rsiTop = macdBottom + panelGap;
  const rsiBottom = rsiTop + rsiHeight;
  const height = rsiBottom + bottom;
  const bodyWidth = Math.max(2, Math.min(5, stepX * 0.58));
  const xAt = (index: number) => left + stepX * index + stepX / 2;
  const ticks = buildChartTicks(candles);

  const ema20 = candles.map((item) => item.ema20);
  const ema50 = candles.map((item) => item.ema50);
  const sma200 = candles.map((item) => item.sma200);
  const tenkan = candles.map((item) => item.ichimoku_tenkan);
  const kijun = candles.map((item) => item.ichimoku_kijun);
  const cloudA = candles.map((item) => item.ichimoku_cloud_a);
  const cloudB = candles.map((item) => item.ichimoku_cloud_b);
  const macdLine = candles.map((item) => item.macd_line);
  const macdSignal = candles.map((item) => item.macd_signal);
  const macdHist = candles.map((item) => item.macd_hist);
  const rsi = candles.map((item) => item.rsi);

  const priceValues = candles
    .flatMap((item) => [
      item.high,
      item.low,
      item.ema20,
      item.ema50,
      item.sma200,
      item.ichimoku_tenkan,
      item.ichimoku_kijun,
      item.ichimoku_cloud_a,
      item.ichimoku_cloud_b
    ])
    .filter(isFiniteNumber);
  const maxPrice = Math.max(...priceValues);
  const minPrice = Math.min(...priceValues);
  const priceSpan = Math.max(maxPrice - minPrice, 1);
  const scalePrice = (value: number) => priceTop + ((maxPrice - value) / priceSpan) * priceHeight;

  const macdValues = [...macdLine, ...macdSignal, ...macdHist, 0].filter(isFiniteNumber);
  const maxMacd = Math.max(...macdValues);
  const minMacd = Math.min(...macdValues);
  const macdSpan = Math.max(maxMacd - minMacd, 1);
  const scaleMacd = (value: number) => macdTop + ((maxMacd - value) / macdSpan) * macdHeight;

  const scaleRsi = (value: number) => rsiTop + ((100 - value) / 100) * rsiHeight;

  const cloudPath = buildAreaPath(cloudA, cloudB, xAt, scalePrice);
  const ema20Path = buildSeriesPath(ema20, xAt, scalePrice);
  const ema50Path = buildSeriesPath(ema50, xAt, scalePrice);
  const sma200Path = buildSeriesPath(sma200, xAt, scalePrice);
  const tenkanPath = buildSeriesPath(tenkan, xAt, scalePrice);
  const kijunPath = buildSeriesPath(kijun, xAt, scalePrice);
  const cloudAPath = buildSeriesPath(cloudA, xAt, scalePrice);
  const cloudBPath = buildSeriesPath(cloudB, xAt, scalePrice);
  const macdLinePath = buildSeriesPath(macdLine, xAt, scaleMacd);
  const macdSignalPath = buildSeriesPath(macdSignal, xAt, scaleMacd);
  const rsiPath = buildSeriesPath(rsi, xAt, scaleRsi);

  return (
    <div className="trend-tool-chart">
      <svg
        viewBox={`0 0 ${width} ${height}`}
        role="img"
        aria-label={lang === 'ko' ? '최근 200일 캔들과 MACD RSI 차트' : 'Last 200 daily candles with MACD and RSI'}
      >
        <rect x="0" y="0" width={width} height={height} rx="22" fill="#fffdf6" />
        <rect x={left} y={priceTop} width={plotWidth} height={priceHeight} fill="#fffdf6" />
        <rect x={left} y={macdTop} width={plotWidth} height={macdHeight} fill="#faf7ef" />
        <rect x={left} y={rsiTop} width={plotWidth} height={rsiHeight} fill="#f8f4ea" />

        {[0, 0.25, 0.5, 0.75, 1].map((ratio) => {
          const y = priceTop + priceHeight * ratio;
          const value = maxPrice - priceSpan * ratio;
          return (
            <g key={`price-grid-${ratio}`}>
              <line x1={left} y1={y} x2={width - right} y2={y} stroke="#d8d1c0" strokeDasharray="4 6" />
              <text x={left - 10} y={y + 4} textAnchor="end" fontSize="11" fill="#5f5849">
                {formatNumber(value, lang, 1)}
              </text>
            </g>
          );
        })}

        {cloudPath ? <path d={cloudPath} fill="#d9d0a0" fillOpacity="0.28" stroke="none" /> : null}
        {cloudAPath ? <path d={cloudAPath} fill="none" stroke="#93884f" strokeWidth="1.2" strokeDasharray="5 4" /> : null}
        {cloudBPath ? <path d={cloudBPath} fill="none" stroke="#b0a56a" strokeWidth="1.2" strokeDasharray="5 4" /> : null}
        {sma200Path ? <path d={sma200Path} fill="none" stroke="#111827" strokeWidth="1.6" /> : null}
        {ema20Path ? <path d={ema20Path} fill="none" stroke="#0284c7" strokeWidth="1.8" /> : null}
        {ema50Path ? <path d={ema50Path} fill="none" stroke="#14b8a6" strokeWidth="1.8" /> : null}
        {tenkanPath ? <path d={tenkanPath} fill="none" stroke="#ca8a04" strokeWidth="1.5" /> : null}
        {kijunPath ? <path d={kijunPath} fill="none" stroke="#dc2626" strokeWidth="1.5" /> : null}

        {candles.map((candle, index) => {
          const centerX = xAt(index);
          const openY = scalePrice(candle.open);
          const closeY = scalePrice(candle.close);
          const highY = scalePrice(candle.high);
          const lowY = scalePrice(candle.low);
          const rising = candle.close >= candle.open;
          const bodyY = Math.min(openY, closeY);
          const bodyHeight = Math.max(Math.abs(closeY - openY), 1.5);
          const bodyColor = rising ? '#155e52' : '#9f2f2f';

          return (
            <g key={`candle-${candle.date}`}>
              <line x1={centerX} y1={highY} x2={centerX} y2={lowY} stroke={bodyColor} strokeWidth="1.1" />
              <rect
                x={centerX - bodyWidth / 2}
                y={bodyY}
                width={bodyWidth}
                height={bodyHeight}
                rx="1"
                fill={rising ? '#d3ece2' : '#f5d8d8'}
                stroke={bodyColor}
                strokeWidth="1"
              />
            </g>
          );
        })}

        {[minMacd, 0, maxMacd].map((value, index) => {
          const y = scaleMacd(value);
          return (
            <g key={`macd-grid-${index}-${value}`}>
              <line x1={left} y1={y} x2={width - right} y2={y} stroke="#d8d1c0" strokeDasharray={value === 0 ? undefined : '4 6'} />
              <text x={left - 10} y={y + 4} textAnchor="end" fontSize="11" fill="#5f5849">
                {formatNumber(value, lang, 2)}
              </text>
            </g>
          );
        })}

        {candles.map((candle, index) => {
          const value = candle.macd_hist;
          if (!isFiniteNumber(value)) return null;
          const x = xAt(index) - bodyWidth / 1.5;
          const y = scaleMacd(Math.max(value, 0));
          const zeroY = scaleMacd(0);
          return (
            <rect
              key={`macd-hist-${candle.date}`}
              x={x}
              y={Math.min(y, zeroY)}
              width={Math.max(2, bodyWidth * 1.15)}
              height={Math.max(Math.abs(zeroY - y), 1)}
              fill={value >= 0 ? '#81c784' : '#ef9a9a'}
              opacity="0.88"
            />
          );
        })}
        {macdLinePath ? <path d={macdLinePath} fill="none" stroke="#1d4ed8" strokeWidth="1.7" /> : null}
        {macdSignalPath ? <path d={macdSignalPath} fill="none" stroke="#f97316" strokeWidth="1.7" /> : null}

        {[30, 50, 70].map((value) => {
          const y = scaleRsi(value);
          return (
            <g key={`rsi-grid-${value}`}>
              <line x1={left} y1={y} x2={width - right} y2={y} stroke="#d8d1c0" strokeDasharray="4 6" />
              <text x={left - 10} y={y + 4} textAnchor="end" fontSize="11" fill="#5f5849">
                {value}
              </text>
            </g>
          );
        })}
        {rsiPath ? <path d={rsiPath} fill="none" stroke="#7c3aed" strokeWidth="1.8" /> : null}

        {ticks.map((tick, index) => (
          <text
            key={`date-tick-${tick}-${index}`}
            x={index === 0 ? xAt(0) : index === 1 ? width / 2 : xAt(Math.max(candles.length - 1, 0))}
            y={height - 10}
            textAnchor={index === 0 ? 'start' : index === 1 ? 'middle' : 'end'}
            fontSize="11"
            fill="#5f5849"
          >
            {formatDate(tick, lang)}
          </text>
        ))}
      </svg>
    </div>
  );
}

export function TrendAnalyzerFeatureCard({ lang }: { lang: SiteLang }) {
  const copy = TOOL_COPY[lang];

  return (
    <section className="tool-feature-card" aria-label={copy.featureTitle}>
      <div className="tool-feature-card__body">
        <p className="tool-feature-card__eyebrow">{copy.featureEyebrow}</p>
        <h2>{copy.featureTitle}</h2>
        <p>{copy.featureDescription}</p>
      </div>
      <Link className="tool-feature-card__link" to={`/${lang}/tools/${TREND_TOOL_SLUG}/`}>
        {copy.featureCta}
      </Link>
    </section>
  );
}

export function TrendAnalyzerToolScreen({ lang }: { lang: SiteLang }) {
  const copy = TOOL_COPY[lang];
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [payload, setPayload] = useState<TrendPayload | null>(null);
  const [error, setError] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const candles = payload?.chart_200d?.candles || [];
  const indicatorSnapshot = payload?.indicator_snapshot || {};
  const activeTicker = payload?.meta?.ticker || '-';
  const localizedTrendLabel = payload
    ? lang === 'ko'
      ? payload.current_state.trend_state_label_ko
      : titleCase(payload.current_state.trend_state_label)
    : '-';
  const summaryBullets =
    payload && (lang === 'ko' ? payload.current_state.summary_bullets_ko : payload.current_state.summary_bullets_en)
      ? (lang === 'ko' ? payload.current_state.summary_bullets_ko : payload.current_state.summary_bullets_en) || []
      : [];
  const detailSections =
    payload && (lang === 'ko' ? payload.current_state.detail_sections_ko : payload.current_state.detail_sections_en)
      ? (lang === 'ko' ? payload.current_state.detail_sections_ko : payload.current_state.detail_sections_en) || []
      : [];
  const fileLabel = fileNameOrFallback(selectedFile, copy.fileEmpty);

  const rangeMetrics: RangeMetric[] = payload
    ? [
        {
          label: copy.strength,
          value: payload.current_state.trend_strength_score,
          min: 0,
          max: 100,
          lowLabel: copy.lowLabel,
          midLabel: copy.midLabel,
          highLabel: copy.highLabel
        },
        {
          label: copy.conviction,
          value: payload.current_state.trend_conviction_score,
          min: 0,
          max: 100,
          lowLabel: copy.lowLabel,
          midLabel: copy.midLabel,
          highLabel: copy.highLabel
        },
        {
          label: copy.risk,
          value: payload.current_state.transition_risk_score,
          min: 0,
          max: 100,
          lowLabel: copy.stableLabel,
          midLabel: copy.elevatedLabel,
          highLabel: copy.riskHighLabel
        },
        {
          label: copy.confidence,
          value: payload.current_state.confidence_score,
          min: 0,
          max: 100,
          lowLabel: copy.lowLabel,
          midLabel: copy.midLabel,
          highLabel: copy.highLabel
        },
        {
          label: copy.direction,
          value: Number(payload.current_state.direction_score),
          min: -100,
          max: 100,
          lowLabel: copy.bearishLabel,
          midLabel: copy.neutralLabel,
          highLabel: copy.bullishLabel,
          signed: true
        },
        {
          label: copy.momentum,
          value: Number(payload.current_state.momentum_score),
          min: -100,
          max: 100,
          lowLabel: copy.bearishLabel,
          midLabel: copy.neutralLabel,
          highLabel: copy.bullishLabel,
          signed: true
        },
        {
          label: copy.volatility,
          value: Number(payload.current_state.volatility_regime_score),
          min: 0,
          max: 100,
          lowLabel: copy.lowLabel,
          midLabel: copy.midLabel,
          highLabel: copy.highLabel
        },
        {
          label: copy.volume,
          value: Number(payload.current_state.volume_confirmation_score),
          min: -100,
          max: 100,
          lowLabel: copy.bearishLabel,
          midLabel: copy.neutralLabel,
          highLabel: copy.bullishLabel,
          signed: true
        }
      ].filter((item) => isFiniteNumber(item.value))
    : [];

  const snapshotItems = [
    { label: copy.lastClose, value: indicatorSnapshot.close },
    { label: copy.ema20Legend, value: indicatorSnapshot.ema20 },
    { label: copy.ema50Legend, value: indicatorSnapshot.ema50 },
    { label: copy.sma200Legend, value: indicatorSnapshot.sma200 },
    { label: copy.tenkanLegend, value: indicatorSnapshot.ichimoku_tenkan },
    { label: copy.kijunLegend, value: indicatorSnapshot.ichimoku_kijun },
    { label: `${copy.cloudLegend} A`, value: indicatorSnapshot.ichimoku_cloud_a },
    { label: `${copy.cloudLegend} B`, value: indicatorSnapshot.ichimoku_cloud_b },
    { label: copy.rsiLegend, value: indicatorSnapshot.rsi },
    { label: copy.macdLegend, value: indicatorSnapshot.macd_line },
    { label: copy.signalLegend, value: indicatorSnapshot.macd_signal },
    { label: 'MACD Hist', value: indicatorSnapshot.macd_hist }
  ].filter((item) => isFiniteNumber(item.value));

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextFile = event.target.files?.[0] || null;
    setSelectedFile(nextFile);
    setError('');
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!selectedFile) {
      setError(lang === 'ko' ? '다운로더가 만든 CSV 파일을 먼저 선택하세요.' : 'Choose the downloader-generated CSV file first.');
      return;
    }

    setIsAnalyzing(true);
    setError('');

    try {
      const response = await analyzeTrendCsv(selectedFile);
      setPayload(response.payload);
    } catch (analysisError) {
      setPayload(null);
      setError(analysisError instanceof Error ? analysisError.message : lang === 'ko' ? '분석에 실패했습니다.' : 'Analysis failed.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <section className="page-section trend-tool-page">
      <div className="container">
        <div className="trend-tool-shell">
          <header className="trend-tool-head">
            <p className="trend-tool-head__eyebrow">{copy.eyebrow}</p>
            <h1>{copy.title}</h1>
            <p>{copy.description}</p>
          </header>

          <section className="trend-tool-panel trend-tool-panel--info">
            <div className="trend-tool-panel__head">
              <div>
                <h2>{copy.downloadTitle}</h2>
                <p>{copy.downloadBody}</p>
              </div>
            </div>
            <div className="trend-tool-downloads">
              <a className="trend-tool-downloads__link" href={TREND_FETCHER_MAC_URL} target="_blank" rel="noreferrer">
                {copy.macDownload}
              </a>
              <a className="trend-tool-downloads__link" href={TREND_FETCHER_WINDOWS_URL} target="_blank" rel="noreferrer">
                {copy.windowsDownload}
              </a>
              <a className="trend-tool-downloads__link trend-tool-downloads__link--ghost" href={TREND_FETCHER_LOCAL_RUN_URL} target="_blank" rel="noreferrer">
                {copy.pythonGuide}
              </a>
              <a className="trend-tool-downloads__link trend-tool-downloads__link--ghost" href={TREND_FETCHER_REPO_URL} target="_blank" rel="noreferrer">
                {copy.repoLink}
              </a>
            </div>
            <p className="trend-tool-downloads__note">{copy.downloadNote}</p>
            <div className="trend-tool-python-fallback">
              <p>{copy.pythonIntro}</p>
              <pre>
                <code>{copy.pythonCommands.join('\n')}</code>
              </pre>
            </div>
          </section>

          <form className="trend-tool-form" onSubmit={handleSubmit}>
            <label className="trend-tool-form__field">
              <span>{copy.fileLabel}</span>
              <div className="trend-tool-upload-row">
                <label className="trend-tool-file-button">
                  <input type="file" accept=".csv,text/csv" onChange={handleFileChange} />
                  <span>{copy.fileButton}</span>
                </label>
                <span className="trend-tool-file-name">{fileLabel}</span>
              </div>
              <p className="trend-tool-form__hint">{copy.fileHint}</p>
            </label>

            <div className="trend-tool-form__footer">
              <button type="submit" disabled={isAnalyzing}>
                {isAnalyzing ? copy.processing : copy.submit}
              </button>
              <p className="trend-tool-form__note">{copy.privacyNotice}</p>
            </div>

            {error ? <p className="trend-tool-form__error">{error}</p> : null}
          </form>

          <div className="trend-tool-status">
            <span>
              {copy.activeTicker}: <strong>{activeTicker}</strong>
            </span>
            <span>
              {copy.fileStatus}: <strong>{fileLabel}</strong>
            </span>
            {payload ? (
              <>
                <span>
                  {copy.asOf}: <strong>{formatDate(payload.meta.as_of_date, lang)}</strong>
                </span>
                <span>
                  {copy.window}: <strong>{formatWindowLabel(payload.meta.window_bars, lang)}</strong>
                </span>
                <span>
                  {copy.trend}: <strong>{localizedTrendLabel}</strong>
                </span>
              </>
            ) : null}
          </div>

          {payload ? (
            <>
              <section className="trend-tool-panel trend-tool-panel--summary">
                <div className="trend-tool-panel__head">
                  <div>
                    <h2>{copy.keySummaryTitle}</h2>
                    <p>{localizedTrendLabel}</p>
                  </div>
                </div>
                <ul className="trend-tool-bullet-list">
                  {summaryBullets.map((item, index) => (
                    <li key={`summary-bullet-${index}`}>{item}</li>
                  ))}
                </ul>
              </section>

              <section className="trend-tool-panel">
                <div className="trend-tool-panel__head">
                  <div>
                    <h2>{copy.chartTitle}</h2>
                    <p>{copy.chartSubtitle}</p>
                  </div>
                  <div className="trend-tool-legend">
                    <span className="trend-tool-legend__item trend-tool-legend__item--sky">{copy.ema20Legend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--teal">{copy.ema50Legend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--ink">{copy.sma200Legend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--gold">{copy.tenkanLegend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--red">{copy.kijunLegend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--sand">{copy.cloudLegend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--blue">{copy.macdLegend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--orange">{copy.signalLegend}</span>
                    <span className="trend-tool-legend__item trend-tool-legend__item--violet">{copy.rsiLegend}</span>
                  </div>
                </div>
                <CombinedTrendChart candles={candles} lang={lang} />
              </section>

              <section className="trend-tool-result">
                <div className="trend-tool-result__head">
                  <h2>{copy.resultTitle}</h2>
                </div>

                <div className="trend-tool-range-grid">
                  {rangeMetrics.map((metric) => {
                    const position = rangePosition(metric.value, metric.min, metric.max);
                    return (
                      <article key={`metric-${metric.label}`} className="trend-tool-range-card">
                        <div className="trend-tool-range-card__head">
                          <span>{metric.label}</span>
                          <strong>{formatMetricValue(metric.value, lang, metric.digits ?? 1, Boolean(metric.signed))}</strong>
                        </div>
                        <div className="trend-tool-range-track">
                          <div className="trend-tool-range-fill" style={{ width: `${position}%` }} />
                          <span className="trend-tool-range-marker" style={{ left: `${position}%` }} />
                        </div>
                        <div className="trend-tool-range-scale">
                          <span>{metric.lowLabel}</span>
                          <span>{metric.midLabel}</span>
                          <span>{metric.highLabel}</span>
                        </div>
                        <p className="trend-tool-range-meta">{buildRangeMeta(metric, copy, lang)}</p>
                      </article>
                    );
                  })}
                </div>

                <div className="trend-tool-analysis-grid">
                  <article className="trend-tool-panel">
                    <div className="trend-tool-panel__head">
                      <div>
                        <h2>{copy.summaryTitle}</h2>
                        <p>{localizedTrendLabel}</p>
                      </div>
                    </div>
                    <div className="trend-tool-detail-stack">
                      {detailSections.map((item, index) => (
                        <p key={`detail-section-${index}`} className="trend-tool-summary">
                          {item}
                        </p>
                      ))}
                    </div>
                  </article>

                  <article className="trend-tool-panel">
                    <div className="trend-tool-panel__head">
                      <div>
                        <h2>{copy.snapshotTitle}</h2>
                        <p>{payload.meta.ticker}</p>
                      </div>
                    </div>
                    <dl className="trend-tool-metric-list">
                      {snapshotItems.map((item) => (
                        <div key={`snapshot-${item.label}`}>
                          <dt>{item.label}</dt>
                          <dd>{formatNumber(Number(item.value), lang, 2)}</dd>
                        </div>
                      ))}
                    </dl>
                  </article>
                </div>
              </section>
            </>
          ) : (
            <section className="trend-tool-panel trend-tool-panel--empty">
              <h2>{copy.noDataTitle}</h2>
              <p>{copy.noDataBody}</p>
            </section>
          )}
        </div>
      </div>
    </section>
  );
}
